name: Deploy PR Preview to GitHub Pages

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages/pr-<PR_NUMBER>
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_dir: pr-${{ github.event.pull_request.number }}
          keep_files: true
          publish_branch: gh-pages

      - name: Add PR comment with preview link
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ Preview available at:
            https://hog-seruj.github.io/project-AgeTeam01/pr-${{ github.event.pull_request.number }}
